plugins {
    id 'com.android.application'
    id 'androidx.navigation.safeargs'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
    id("org.jetbrains.kotlin.plugin.compose") version "2.0.0"
}

android {
    compileSdk 35
    namespace 'com.abdelrahman.rafaat.notesapp'

    defaultConfig {
        applicationId "com.abdelrahman.rafaat.notesapp"
        minSdk 26
        targetSdk 35
        versionCode 8
        versionName "1.1.8"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        javaCompileOptions {
            annotationProcessorOptions {
                arguments += ["room.schemaLocation": "$projectDir/schemas".toString()]
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures {
        viewBinding true
        compose = true
    }

    kotlinOptions {
        jvmTarget = '11'
    }
    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.15"
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.0'
    implementation 'androidx.preference:preference-ktx:1.2.1'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'

    //Room
    def room_version = "2.6.1"
    implementation "androidx.room:room-runtime:$room_version"
    annotationProcessor "androidx.room:room-compiler:$room_version"
    implementation "androidx.room:room-rxjava3:$room_version"


    //ViewModel
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'

    //lottie
    implementation "com.airbnb.android:lottie:6.1.0"

    //Navigation Graph
    def nav_version = "2.8.5"
    implementation "androidx.navigation:navigation-fragment-ktx:$nav_version"
    implementation "androidx.navigation:navigation-ui-ktx:$nav_version"

    //Passcode
    implementation 'io.github.chaosleung:pinview:1.4.4'

    //toolTip
    implementation 'uk.co.samuelwall:material-tap-target-prompt:3.3.2'

    //AdMob
    implementation 'com.google.android.gms:play-services-ads:23.6.0'

    //facebook Ads
    implementation 'com.facebook.android:audience-network-sdk:6.13.7'

    //In-App Update Library
    implementation 'com.google.android.play:app-update:2.1.0'
    implementation 'com.google.android.play:app-update-ktx:2.1.0'

    //androidx preference
    implementation 'androidx.preference:preference-ktx:1.2.1'

    //Firebase
    implementation platform('com.google.firebase:firebase-bom:33.8.0')
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-crashlytics'

    implementation "androidx.biometric:biometric:1.1.0"

    //RxJava3
    implementation 'io.reactivex.rxjava3:rxandroid:3.0.2'
    implementation 'io.reactivex.rxjava3:rxjava:3.1.5'


    def compose_version = "1.7.6"
    implementation "androidx.compose.ui:ui:$compose_version"
    implementation "androidx.compose.material:material:$compose_version"
    implementation "androidx.compose.ui:ui-tooling:$compose_version"
    implementation "androidx.compose.runtime:runtime:$compose_version"

    implementation "androidx.activity:activity-compose:1.10.0"
    implementation "androidx.navigation:navigation-compose:2.8.5"
}